### ISSUE TITLE
code still runs even when cors complains

### ISSUE THREAD

**Issue by bukinoshita** [possibilities/micro-cors#45]
Am I missing something?

I have this code below:

```js
const microCors = require('micro-cors')
const { send } = require('micro')

const cors = microCors({ origin: 'https://google.com' })

const handler = (req, res) => {
  console.log('> RUN')
  send(res, 200, 'OK')
}

module.exports = cors(handler)
```

If I make a request in the client-side I receive a `cors` warning in my console, but still the code inside `handler` runs, it's not blocked. If I'm not making a request from `https://google.com`, the code shouldn't run and I should receive a warning in the client-side, right?

**Comment by bukinoshita** [comment]
Do we have any update on this?

**Comment by infernalmaster** [comment]
This middleware doesn't block any request. It just adds response `headers` for browser, so it could handle cross-origin request. 

And for now correct usage should be like this. 

const handler = (req, res) => {
  if (req.method === 'OPTIONS') {
    send(res, 204)
  } else {
    console.log('> RUN')
    send(res, 200, 'OK')
  }
}

So browsers sends OPTIONS request first and expects response with correct headers (It ignore body of response). And after that browser do real request.

But as I see express has option [preflightContinue](https://github.com/expressjs/cors/blob/master/lib/index.js#L173) (false by default). So it sends empty response for OPTIONS request by default. Maybe we should do the same

**Comment by infernalmaster** [comment]
I can prepare PR. @tim-phillips what do you think about that?

**Comment by tim-phillips** [comment]
That's correct, we should return an empty response for an OPTIONS request by default. 

Let's return an empty `200` on a preflight request, that seems to be what people are doing even though I don't think it's mentioned in the spec (I know `expressjs/cors` returns `204` but it seems to be redundant since we know we should get an empty response and that is `OK`).

- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests (scroll down)
- https://docs.microsoft.com/en-us/rest/api/storageservices/preflight-table-request#status-code
- https://stackoverflow.com/questions/46026409/what-are-proper-status-codes-for-cors-preflight-requests
- https://www.html5rocks.com/en/tutorials/cors/
- https://www.html5rocks.com/static/images/cors_server_flowchart.png

![cors_server_flowchart](https://user-images.githubusercontent.com/3578574/48804081-855ed880-ecc8-11e8-8c7b-6bb23597dc5f.png)

Let's not yet do `preflightContinue`, I'm not convinced it's necessary. 

Thanks for reviving this. A PR would be most welcome :)

**Comment by bukinoshita** [comment]
Thanks for update and explanation!

**Comment by tim-phillips** [comment]
This is merged in the `v1` branch. 

Happy holidays and new year!
